# misc settings
data_dir: ..\..\input
config_dir: configs\airport.san

# non-skim inputs
maz_input_fname: land_use.csv
hh_input_fname: households.csv
employee_park_fname: airport_employee_park.SAN.csv
arrival_sched_probs_fname: airport_arrival.SAN.csv
departure_sched_probs_fname: airport_departure.SAN.csv
purpose_probs_input_fname: airport_purpose.SAN.csv
party_size_probs_input_fname: airport_party.SAN.csv
nights_probs_input_fname: airport_nights.SAN.csv
income_probs_input_fname: airport_income.SAN.csv
ext_station_probs_input_fname: InternalExternalDestinationChoiceAlternatives.csv

#outputs
sched_probs_output_name: tour_scheduling_probs.csv
# output data
households_output_fname: households_airport.san.csv
persons_output_fname: persons_airport.san.csv
tours_output_fname: tours_airport.san.csv
maz_output_fname: land_use.san.csv

airport_code: SAN

# output configs
tour_scheduling_probs_output_fname: tour_scheduling_probs.csv
tour_scheduling_alts_output_fname: tour_departure_and_duration_alternatives.csv
stop_frequency_alts_output_fname: stop_frequency_alternatives.csv
stop_frequency_coeffs_output_formattable_fname: 'stop_frequency_coefficients_{purpose}.csv'
stop_frequency_expressions_output_formattable_fname: 'stop_frequency_{purpose}.csv'
trip_purpose_probs_output_fname: trip_purpose_probs.csv
trip_scheduling_probs_output_fname: trip_scheduling_probs.csv

# Tours
tours:
  num_enplanements: {airport-san-enplanements:}
  avg_party_size: {airport-san-avgPartySize:}
  annualization_factor: {airport-annualizationFactor:}
  connecting: {airport-san-connecting:}
  airport_mgra: 11249

