REMOVE_COLUMNS_TRIPS:
  - DRIVEALONE_NOTR_EA_LOW
  - SHARED2_NOTR_EA_LOW
  - SHARED3_NOTR_EA_LOW
  - DRIVEALONE_TR_EA_LOW
  - SHARED2_TR_EA_LOW
  - SHARED3_TR_EA_LOW
  - DRIVEALONE_NOTR_EA_MED
  - SHARED2_NOTR_EA_MED
  - SHARED3_NOTR_EA_MED
  - DRIVEALONE_TR_EA_MED
  - SHARED2_TR_EA_MED
  - SHARED3_TR_EA_MED
  - DRIVEALONE_NOTR_EA_HIGH
  - SHARED2_NOTR_EA_HIGH
  - SHARED3_NOTR_EA_HIGH
  - DRIVEALONE_TR_EA_HIGH
  - SHARED2_TR_EA_HIGH
  - SHARED3_TR_EA_HIGH
  - WALK_LOC_EA
  - WALK_PRM_EA
  - WALK_MIX_EA
  - PNR_LOCOUT_EA
  - PNR_PRMOUT_EA
  - PNR_MIXOUT_EA
  - KNR_LOCOUT_EA
  - KNR_PRMOUT_EA
  - KNR_MIXOUT_EA
  - TNC_LOCOUT_EA
  - TNC_PRMOUT_EA
  - TNC_MIXOUT_EA
  - PNR_LOCIN_EA
  - PNR_PRMIN_EA
  - PNR_MIXIN_EA
  - KNR_LOCIN_EA
  - KNR_PRMIN_EA
  - KNR_MIXIN_EA
  - TNC_LOCIN_EA
  - TNC_PRMIN_EA
  - TNC_MIXIN_EA
  - BIKE_EA
  - WALK_EA
  - DRIVEALONE_NOTR_AM_LOW
  - SHARED2_NOTR_AM_LOW
  - SHARED3_NOTR_AM_LOW
  - DRIVEALONE_TR_AM_LOW
  - SHARED2_TR_AM_LOW
  - SHARED3_TR_AM_LOW
  - DRIVEALONE_NOTR_AM_MED
  - SHARED2_NOTR_AM_MED
  - SHARED3_NOTR_AM_MED
  - DRIVEALONE_TR_AM_MED
  - SHARED2_TR_AM_MED
  - SHARED3_TR_AM_MED
  - DRIVEALONE_NOTR_AM_HIGH
  - SHARED2_NOTR_AM_HIGH
  - SHARED3_NOTR_AM_HIGH
  - DRIVEALONE_TR_AM_HIGH
  - SHARED2_TR_AM_HIGH
  - SHARED3_TR_AM_HIGH
  - WALK_LOC_AM
  - WALK_PRM_AM
  - WALK_MIX_AM
  - PNR_LOCOUT_AM
  - PNR_PRMOUT_AM
  - PNR_MIXOUT_AM
  - KNR_LOCOUT_AM
  - KNR_PRMOUT_AM
  - KNR_MIXOUT_AM
  - TNC_LOCOUT_AM
  - TNC_PRMOUT_AM
  - TNC_MIXOUT_AM
  - PNR_LOCIN_AM
  - PNR_PRMIN_AM
  - PNR_MIXIN_AM
  - KNR_LOCIN_AM
  - KNR_PRMIN_AM
  - KNR_MIXIN_AM
  - TNC_LOCIN_AM
  - TNC_PRMIN_AM
  - TNC_MIXIN_AM
  - BIKE_AM
  - WALK_AM
  - DRIVEALONE_NOTR_MD_LOW
  - SHARED2_NOTR_MD_LOW
  - SHARED3_NOTR_MD_LOW
  - DRIVEALONE_TR_MD_LOW
  - SHARED2_TR_MD_LOW
  - SHARED3_TR_MD_LOW
  - DRIVEALONE_NOTR_MD_MED
  - SHARED2_NOTR_MD_MED
  - SHARED3_NOTR_MD_MED
  - DRIVEALONE_TR_MD_MED
  - SHARED2_TR_MD_MED
  - SHARED3_TR_MD_MED
  - DRIVEALONE_NOTR_MD_HIGH
  - SHARED2_NOTR_MD_HIGH
  - SHARED3_NOTR_MD_HIGH
  - DRIVEALONE_TR_MD_HIGH
  - SHARED2_TR_MD_HIGH
  - SHARED3_TR_MD_HIGH
  - WALK_LOC_MD
  - WALK_PRM_MD
  - WALK_MIX_MD
  - PNR_LOCOUT_MD
  - PNR_PRMOUT_MD
  - PNR_MIXOUT_MD
  - KNR_LOCOUT_MD
  - KNR_PRMOUT_MD
  - KNR_MIXOUT_MD
  - TNC_LOCOUT_MD
  - TNC_PRMOUT_MD
  - TNC_MIXOUT_MD
  - PNR_LOCIN_MD
  - PNR_PRMIN_MD
  - PNR_MIXIN_MD
  - KNR_LOCIN_MD
  - KNR_PRMIN_MD
  - KNR_MIXIN_MD
  - TNC_LOCIN_MD
  - TNC_PRMIN_MD
  - TNC_MIXIN_MD
  - BIKE_MD
  - WALK_MD
  - DRIVEALONE_NOTR_PM_LOW
  - SHARED2_NOTR_PM_LOW
  - SHARED3_NOTR_PM_LOW
  - DRIVEALONE_TR_PM_LOW
  - SHARED2_TR_PM_LOW
  - SHARED3_TR_PM_LOW
  - DRIVEALONE_NOTR_PM_MED
  - SHARED2_NOTR_PM_MED
  - SHARED3_NOTR_PM_MED
  - DRIVEALONE_TR_PM_MED
  - SHARED2_TR_PM_MED
  - SHARED3_TR_PM_MED
  - DRIVEALONE_NOTR_PM_HIGH
  - SHARED2_NOTR_PM_HIGH
  - SHARED3_NOTR_PM_HIGH
  - DRIVEALONE_TR_PM_HIGH
  - SHARED2_TR_PM_HIGH
  - SHARED3_TR_PM_HIGH
  - WALK_LOC_PM
  - WALK_PRM_PM
  - WALK_MIX_PM
  - PNR_LOCOUT_PM
  - PNR_PRMOUT_PM
  - PNR_MIXOUT_PM
  - KNR_LOCOUT_PM
  - KNR_PRMOUT_PM
  - KNR_MIXOUT_PM
  - TNC_LOCOUT_PM
  - TNC_PRMOUT_PM
  - TNC_MIXOUT_PM
  - PNR_LOCIN_PM
  - PNR_PRMIN_PM
  - PNR_MIXIN_PM
  - KNR_LOCIN_PM
  - KNR_PRMIN_PM
  - KNR_MIXIN_PM
  - TNC_LOCIN_PM
  - TNC_PRMIN_PM
  - TNC_MIXIN_PM
  - BIKE_PM
  - WALK_PM
  - DRIVEALONE_NOTR_EV_LOW
  - SHARED2_NOTR_EV_LOW
  - SHARED3_NOTR_EV_LOW
  - DRIVEALONE_TR_EV_LOW
  - SHARED2_TR_EV_LOW
  - SHARED3_TR_EV_LOW
  - DRIVEALONE_NOTR_EV_MED
  - SHARED2_NOTR_EV_MED
  - SHARED3_NOTR_EV_MED
  - DRIVEALONE_TR_EV_MED
  - SHARED2_TR_EV_MED
  - SHARED3_TR_EV_MED
  - DRIVEALONE_NOTR_EV_HIGH
  - SHARED2_NOTR_EV_HIGH
  - SHARED3_NOTR_EV_HIGH
  - DRIVEALONE_TR_EV_HIGH
  - SHARED2_TR_EV_HIGH
  - SHARED3_TR_EV_HIGH
  - WALK_LOC_EV
  - WALK_PRM_EV
  - WALK_MIX_EV
  - PNR_LOCOUT_EV
  - PNR_PRMOUT_EV
  - PNR_MIXOUT_EV
  - KNR_LOCOUT_EV
  - KNR_PRMOUT_EV
  - KNR_MIXOUT_EV
  - TNC_LOCOUT_EV
  - TNC_PRMOUT_EV
  - TNC_MIXOUT_EV
  - PNR_LOCIN_EV
  - PNR_PRMIN_EV
  - PNR_MIXIN_EV
  - KNR_LOCIN_EV
  - KNR_PRMIN_EV
  - KNR_MIXIN_EV
  - TNC_LOCIN_EV
  - TNC_PRMIN_EV
  - TNC_MIXIN_EV
  - BIKE_EV
  - WALK_EV
  - DRIVEALONE_EA_LOW
  - SHARED2_EA_LOW
  - SHARED3_EA_LOW
  - DRIVEALONE_EA_MED
  - SHARED2_EA_MED
  - SHARED3_EA_MED
  - DRIVEALONE_EA_HIGH
  - SHARED2_EA_HIGH
  - SHARED3_EA_HIGH
  - WALK_SET_set1_EA
  - WALK_SET_set2_EA
  - WALK_SET_set3_EA
  - PNROUT_SET_set1_EA
  - PNROUT_SET_set2_EA
  - PNROUT_SET_set3_EA
  - KNROUT_SET_set1_EA
  - KNROUT_SET_set2_EA
  - KNROUT_SET_set3_EA
  - TNCOUT_SET_set1_EA
  - TNCOUT_SET_set2_EA
  - TNCOUT_SET_set3_EA
  - PNRIN_SET_set1_EA
  - PNRIN_SET_set2_EA
  - PNRIN_SET_set3_EA
  - KNRIN_SET_set1_EA
  - KNRIN_SET_set2_EA
  - KNRIN_SET_set3_EA
  - TNCIN_SET_set1_EA
  - TNCIN_SET_set2_EA
  - TNCIN_SET_set3_EA
  - DRIVEALONE_AM_LOW
  - SHARED2_AM_LOW
  - SHARED3_AM_LOW
  - DRIVEALONE_AM_MED
  - SHARED2_AM_MED
  - SHARED3_AM_MED
  - DRIVEALONE_AM_HIGH
  - SHARED2_AM_HIGH
  - SHARED3_AM_HIGH
  - WALK_SET_set1_AM
  - WALK_SET_set2_AM
  - WALK_SET_set3_AM
  - PNROUT_SET_set1_AM
  - PNROUT_SET_set2_AM
  - PNROUT_SET_set3_AM
  - KNROUT_SET_set1_AM
  - KNROUT_SET_set2_AM
  - KNROUT_SET_set3_AM
  - TNCOUT_SET_set1_AM
  - TNCOUT_SET_set2_AM
  - TNCOUT_SET_set3_AM
  - PNRIN_SET_set1_AM
  - PNRIN_SET_set2_AM
  - PNRIN_SET_set3_AM
  - KNRIN_SET_set1_AM
  - KNRIN_SET_set2_AM
  - KNRIN_SET_set3_AM
  - TNCIN_SET_set1_AM
  - TNCIN_SET_set2_AM
  - TNCIN_SET_set3_AM
  - DRIVEALONE_MD_LOW
  - SHARED2_MD_LOW
  - SHARED3_MD_LOW
  - DRIVEALONE_MD_MED
  - SHARED2_MD_MED
  - SHARED3_MD_MED
  - DRIVEALONE_MD_HIGH
  - SHARED2_MD_HIGH
  - SHARED3_MD_HIGH
  - WALK_SET_set1_MD
  - WALK_SET_set2_MD
  - WALK_SET_set3_MD
  - PNROUT_SET_set1_MD
  - PNROUT_SET_set2_MD
  - PNROUT_SET_set3_MD
  - KNROUT_SET_set1_MD
  - KNROUT_SET_set2_MD
  - KNROUT_SET_set3_MD
  - TNCOUT_SET_set1_MD
  - TNCOUT_SET_set2_MD
  - TNCOUT_SET_set3_MD
  - PNRIN_SET_set1_MD
  - PNRIN_SET_set2_MD
  - PNRIN_SET_set3_MD
  - KNRIN_SET_set1_MD
  - KNRIN_SET_set2_MD
  - KNRIN_SET_set3_MD
  - TNCIN_SET_set1_MD
  - TNCIN_SET_set2_MD
  - TNCIN_SET_set3_MD
  - DRIVEALONE_PM_LOW
  - SHARED2_PM_LOW
  - SHARED3_PM_LOW
  - DRIVEALONE_PM_MED
  - SHARED2_PM_MED
  - SHARED3_PM_MED
  - DRIVEALONE_PM_HIGH
  - SHARED2_PM_HIGH
  - SHARED3_PM_HIGH
  - WALK_SET_set1_PM
  - WALK_SET_set2_PM
  - WALK_SET_set3_PM
  - PNROUT_SET_set1_PM
  - PNROUT_SET_set2_PM
  - PNROUT_SET_set3_PM
  - KNROUT_SET_set1_PM
  - KNROUT_SET_set2_PM
  - KNROUT_SET_set3_PM
  - TNCOUT_SET_set1_PM
  - TNCOUT_SET_set2_PM
  - TNCOUT_SET_set3_PM
  - PNRIN_SET_set1_PM
  - PNRIN_SET_set2_PM
  - PNRIN_SET_set3_PM
  - KNRIN_SET_set1_PM
  - KNRIN_SET_set2_PM
  - KNRIN_SET_set3_PM
  - TNCIN_SET_set1_PM
  - TNCIN_SET_set2_PM
  - TNCIN_SET_set3_PM
  - DRIVEALONE_EV_LOW
  - SHARED2_EV_LOW
  - SHARED3_EV_LOW
  - DRIVEALONE_EV_MED
  - SHARED2_EV_MED
  - SHARED3_EV_MED
  - DRIVEALONE_EV_HIGH
  - SHARED2_EV_HIGH
  - SHARED3_EV_HIGH
  - WALK_SET_set1_EV
  - WALK_SET_set2_EV
  - WALK_SET_set3_EV
  - PNROUT_SET_set1_EV
  - PNROUT_SET_set2_EV
  - PNROUT_SET_set3_EV
  - KNROUT_SET_set1_EV
  - KNROUT_SET_set2_EV
  - KNROUT_SET_set3_EV
  - TNCOUT_SET_set1_EV
  - TNCOUT_SET_set2_EV
  - TNCOUT_SET_set3_EV
  - PNRIN_SET_set1_EV
  - PNRIN_SET_set2_EV
  - PNRIN_SET_set3_EV
  - KNRIN_SET_set1_EV
  - KNRIN_SET_set2_EV
  - KNRIN_SET_set3_EV
  - TNCIN_SET_set1_EV
  - TNCIN_SET_set2_EV
  - TNCIN_SET_set3_EV
  - DRIVEALONE_EA_low
  - SHARED2_EA_low
  - SHARED3_EA_low
  - DRIVEALONE_EA_med
  - SHARED2_EA_med
  - SHARED3_EA_med
  - DRIVEALONE_EA_high
  - SHARED2_EA_high
  - SHARED3_EA_high
  - TAXI_EA
  - TNC_SINGLE_EA
  - TNC_SHARED_EA
  - DRIVEALONE_AM_low
  - SHARED2_AM_low
  - SHARED3_AM_low
  - DRIVEALONE_AM_med
  - SHARED2_AM_med
  - SHARED3_AM_med
  - DRIVEALONE_AM_high
  - SHARED2_AM_high
  - SHARED3_AM_high
  - TAXI_AM
  - TNC_SINGLE_AM
  - TNC_SHARED_AM
  - DRIVEALONE_MD_low
  - SHARED2_MD_low
  - SHARED3_MD_low
  - DRIVEALONE_MD_med
  - SHARED2_MD_med
  - SHARED3_MD_med
  - DRIVEALONE_MD_high
  - SHARED2_MD_high
  - SHARED3_MD_high
  - TAXI_MD
  - TNC_SINGLE_MD
  - TNC_SHARED_MD
  - DRIVEALONE_PM_low
  - SHARED2_PM_low
  - SHARED3_PM_low
  - DRIVEALONE_PM_med
  - SHARED2_PM_med
  - SHARED3_PM_med
  - DRIVEALONE_PM_high
  - SHARED2_PM_high
  - SHARED3_PM_high
  - TAXI_PM
  - TNC_SINGLE_PM
  - TNC_SHARED_PM
  - DRIVEALONE_EV_low
  - SHARED2_EV_low
  - SHARED3_EV_low
  - DRIVEALONE_EV_med
  - SHARED2_EV_med
  - SHARED3_EV_med
  - DRIVEALONE_EV_high
  - SHARED2_EV_high
  - SHARED3_EV_high
  - TAXI_EV
  - TNC_SINGLE_EV
  - TNC_SHARED_EV
  - is_walk_LOC_transit
  - is_walk_PRM_transit
  - is_walk_MIX_transit
  - is_knr_loc
  - is_knr_prm
  - is_knr_mix
  - is_tnc_loc
  - is_tnc_prm
  - is_tnc_mix
  - is_pnr_loc
  - is_pnr_prm
  - is_pnr_mix
  - is_drivealone
  - is_shared2
  - is_shared3
  - is_walk
  - is_drive_loc
  - is_drive_prm
  - is_drive_mix

REMOVE_COLUMNS_HOUSEHOLDS:
  - dudenbin
  - othercollege_All_Graduate
  - PopEmpDenPerMi
  - remoteAVParking
  - parking_type
  - emp_gov
  - mstallsoth
  - walk_dist_premium_transit
  - mgra.1
  - othercollege_ft_Undergrad
  - gq_mil
  - emp_ag_min
  - hotelroomtotal
  - enrollgrade9to12
  - emp_non_ws_wfh
  - dstallsoth
  - refueling_stations
  - emp_hlth
  - totintbin
  - emp_mil
  - exp_daily
  - parkactive
  - AVGTTS
  - hch_dist
  - emp_whl
  - truckregiontype
  - othercollegeenroll
  - enrollgradekto8
  - empdenbin
  - othercollege_pt_Undergrad
  - dparkcost
  - emp_food
  - emp_ret
  - terminal_time
  - major_All_Graduate
  - duden
  - luxuryroom
  - midpriceroom
  - hh
  - walk_dist_local_bus
  - majorcollege_pt_Undergrad
  - emp_bus_svcs
  - hstallsoth
  - hparkcost
  - emp_retail
  - pseudomsa
  - exp_hourly
  - ech_dist
  - othercollege_All_Undergrad
  - mparkcost
  - effective_acres
  - MicroAccessTime
  - TAZ.1
  - land_acres
  - empden
  - acres
  - emp_fin_res_mgm
  - PCTDETOUR
  - pop
  - majorcollege_All_Undergrad
  - hhp
  - milestocoast
  - popden
  - majorcollege_ft_Undergrad
  - emp_restaurant_bar
  - external_work
  - is_parking_zone
  - emp_amusement
  - external_TAZ
  - totint
  - hhs
  - emp_total
  - emp_mnf
  - dstallssam
  - external_nonwork
  - poe_id
  - is_cbd
  - exp_monthly
  - density_index
  - tot_collegeenroll
  - collegeenroll
  - preschool_target
  - retempden
  - gq_civ
  - household_density
  - numfreehrs
  - i10
  - emp_educ
  - emp_utl
  - emp_con
  - parkarea
  - mstallssam
  - parking_spaces
  - population_density
  - emp_accm
  - end_iteration
  - district27
  - emp_hotel.1
  - employment_density
  - openspaceparkpreserve
  - emp_trn_wrh
  - emp_oth
  - emp_ent
  - beachactive
  - upscaleroom
  - hstallssam
  - adultschenrl
  - external_MAZ
  - emp_hotel
  - ML_DIST
  - emp_non_ws_oth
  - budgetroom
  - economyroom

REMOVE_COLUMNS_LAND_USE:
  - std_wait_1
  - std_wait_2
  - std_wait_3
  - std_wait_4
  - std_wait_5
  - std_wait_6
  - std_wait_7
  - std_wait_8
  - std_wait_9
  - std_wait_10
  - std_wait_11
  - std_wait_12
  - std_wait_13
  - std_wait_14
  - std_wait_15
  - std_wait_16
  - std_wait_17
  - std_wait_18
  - std_wait_19
  - std_wait_20
  - std_wait_21
  - std_wait_22
  - std_wait_23
  - std_wait_24
  - std_wait_25
  - std_wait_26
  - std_wait_27
  - std_wait_28
  - std_wait_29
  - std_wait_30
  - std_wait_31
  - std_wait_32
  - std_wait_33
  - std_wait_34
  - std_wait_35
  - std_wait_36
  - std_wait_37
  - std_wait_38
  - std_wait_39
  - std_wait_40
  - std_wait_41
  - std_wait_42
  - std_wait_43
  - std_wait_44
  - std_wait_45
  - std_wait_46
  - std_wait_47
  - std_wait_48
  - sentri_wait_1
  - sentri_wait_2
  - sentri_wait_3
  - sentri_wait_4
  - sentri_wait_5
  - sentri_wait_6
  - sentri_wait_7
  - sentri_wait_8
  - sentri_wait_9
  - sentri_wait_10
  - sentri_wait_11
  - sentri_wait_12
  - sentri_wait_13
  - sentri_wait_14
  - sentri_wait_15
  - sentri_wait_16
  - sentri_wait_17
  - sentri_wait_18
  - sentri_wait_19
  - sentri_wait_20
  - sentri_wait_21
  - sentri_wait_22
  - sentri_wait_23
  - sentri_wait_24
  - sentri_wait_25
  - sentri_wait_26
  - sentri_wait_27
  - sentri_wait_28
  - sentri_wait_29
  - sentri_wait_30
  - sentri_wait_31
  - sentri_wait_32
  - sentri_wait_33
  - sentri_wait_34
  - sentri_wait_35
  - sentri_wait_36
  - sentri_wait_37
  - sentri_wait_38
  - sentri_wait_39
  - sentri_wait_40
  - sentri_wait_41
  - sentri_wait_42
  - sentri_wait_43
  - sentri_wait_44
  - sentri_wait_45
  - sentri_wait_46
  - sentri_wait_47
  - sentri_wait_48
  - ped_wait_1
  - ped_wait_2
  - ped_wait_3
  - ped_wait_4
  - ped_wait_5
  - ped_wait_6
  - ped_wait_7
  - ped_wait_8
  - ped_wait_9
  - ped_wait_10
  - ped_wait_11
  - ped_wait_12
  - ped_wait_13
  - ped_wait_14
  - ped_wait_15
  - ped_wait_16
  - ped_wait_17
  - ped_wait_18
  - ped_wait_19
  - ped_wait_20
  - ped_wait_21
  - ped_wait_22
  - ped_wait_23
  - ped_wait_24
  - ped_wait_25
  - ped_wait_26
  - ped_wait_27
  - ped_wait_28
  - ped_wait_29
  - ped_wait_30
  - ped_wait_31
  - ped_wait_32
  - ped_wait_33
  - ped_wait_34
  - ped_wait_35
  - ped_wait_36
  - ped_wait_37
  - ped_wait_38
  - ped_wait_39
  - ped_wait_40
  - ped_wait_41
  - ped_wait_42
  - ped_wait_43
  - ped_wait_44
  - ped_wait_45
  - ped_wait_46
  - ped_wait_47
  - ped_wait_48
  - ready_wait_1
  - ready_wait_2
  - ready_wait_3
  - ready_wait_4
  - ready_wait_5
  - ready_wait_6
  - ready_wait_7
  - ready_wait_8
  - ready_wait_9
  - ready_wait_10
  - ready_wait_11
  - ready_wait_12
  - ready_wait_13
  - ready_wait_14
  - ready_wait_15
  - ready_wait_16
  - ready_wait_17
  - ready_wait_18
  - ready_wait_19
  - ready_wait_20
  - ready_wait_21
  - ready_wait_22
  - ready_wait_23
  - ready_wait_24
  - ready_wait_25
  - ready_wait_26
  - ready_wait_27
  - ready_wait_28
  - ready_wait_29
  - ready_wait_30
  - ready_wait_31
  - ready_wait_32
  - ready_wait_33
  - ready_wait_34
  - ready_wait_35
  - ready_wait_36
  - ready_wait_37
  - ready_wait_38
  - ready_wait_39
  - ready_wait_40
  - ready_wait_41
  - ready_wait_42
  - ready_wait_43
  - ready_wait_44
  - ready_wait_45
  - ready_wait_46
  - ready_wait_47
  - ready_wait_48
  - "Unnamed: 0"
  - original_MAZ
  - TAZ.1
  - mgra.1

REORDER_COLUMNS_LAND_USE:
  - scenario_id
  - zone_id
  - mgra
  - TAZ
  - luz_id
  - pseudomsa
  - zip09
  - model
  - pop
  - hhp
  - hs
  - hs_sf
  - hs_mf
  - hs_mh
  - hh
  - hh_sf
  - hh_mf
  - hh_mh
  - hhs
  - gq_civ
  - gq_mil
  - i1
  - i2
  - i3
  - i4
  - i5
  - i6
  - i7
  - i8
  - i9
  - i10
  - preschool_target
  - enrollgradekto8
  - enrollgrade9to12
  - collegeenroll
  - tot_collegeenroll
  - majorcollege_pt_Undergrad
  - majorcollege_ft_Undergrad
  - majorcollege_All_Undergrad
  - major_All_Graduate
  - othercollegeenroll
  - othercollege_pt_Undergrad
  - othercollege_ft_Undergrad
  - othercollege_All_Undergrad
  - othercollege_All_Graduate
  - hotelroomtotal
  - parkactive
  - openspaceparkpreserve
  - beachactive
  - district27
  - milestocoast
  - acres
  - land_acres
  - effective_acres
  - truckregiontype
  - emp_gov
  - emp_mil
  - emp_ag_min
  - emp_bus_svcs
  - emp_fin_res_mgm
  - emp_educ
  - emp_hlth
  - emp_ret
  - emp_trn_wrh
  - emp_con
  - emp_utl
  - emp_mnf
  - emp_whl
  - emp_ent
  - emp_accm
  - emp_food
  - emp_oth
  - emp_non_ws_wfh
  - emp_non_ws_oth
  - emp_total
  - emp_retail
  - emp_amusement
  - emp_hotel
  - totint
  - duden
  - empden
  - popden
  - population_density
  - retempden
  - totintbin
  - empdenbin
  - dudenbin
  - PopEmpDenPerMi
  - ech_dist
  - hch_dist
  - adultschenrl
  - hstallsoth
  - hstallssam
  - numfreehrs
  - dstallsoth
  - dstallssam
  - mstallsoth
  - mstallssam
  - budgetroom
  - economyroom
  - luxuryroom
  - midpriceroom
  - upscaleroom
  - MicroAccessTime
  - remoteAVParking
  - refueling_stations
  - exp_hourly
  - exp_daily
  - exp_monthly
  - parking_type
  - parking_spaces
  - is_parking_zone
  - hparkcost
  - dparkcost
  - mparkcost
  - parkarea
  - poe_id
  - external_work
  - external_nonwork
  - external_TAZ
  - external_MAZ
  - walk_dist_local_bus
  - walk_dist_premium_transit
  - ML_DIST
  - AVGTTS
  - PCTDETOUR
  - terminal_time
  - scenario_guid
  - scenario_ts
  - current_iteration
  - end_iteration