# read trips table post preprocessor and run expressions to code
# additional data fields, with one data fields for each matrix specified below

preprocessor:
  SPEC: write_trip_matrices_annotate_trips_preprocessor
  DF: trips
  TABLES:
    - tours

# divide trip counts by household expansion factor
HH_EXPANSION_WEIGHT_COL: sample_rate  # added when households read in

# save preprocessed trips table to pipeline if desired
SAVE_TRIPS_TABLE: False

MATRICES:
  - file_name: trips_ea.omx
    tables:
      - name: DRIVEALONE_EA
        data_field: DRIVEALONE_EA
      - name: SHARED2_EA
        data_field: SHARED2_EA
      - name: SHARED3_EA
        data_field: SHARED3_EA
      - name: WALK_EA
        data_field: WALK_EA
      - name: BIKE_EA
        data_field: BIKE_EA
  - file_name: trips_ea_tap.omx
    is_tap: True
    tables:
      - name: WALK_TRANSIT_EA
        data_field: WALK_TRANSIT_EA
  - file_name: trips_am.omx
    tables:
      - name: DRIVEALONE_AM
        data_field: DRIVEALONE_AM
      - name: SHARED2_AM
        data_field: SHARED2_AM
      - name: SHARED3_AM
        data_field: SHARED3_AM
      - name: WALK_AM
        data_field: WALK_AM
      - name: BIKE_AM
        data_field: BIKE_AM
  - file_name: trips_am_tap.omx
    is_tap: True
    tables:
      - name: WALK_TRANSIT_AM
        data_field: WALK_TRANSIT_AM
  - file_name: trips_md.omx
    tables:
      - name: DRIVEALONE_MD
        data_field: DRIVEALONE_MD
      - name: SHARED2_MD
        data_field: SHARED2_MD
      - name: SHARED3_MD
        data_field: SHARED3_MD
      - name: WALK_MD
        data_field: WALK_MD
      - name: BIKE_MD
        data_field: BIKE_MD
  - file_name: trips_md_tap.omx
    is_tap: True
    tables:
      - name: WALK_TRANSIT_MD
        data_field: WALK_TRANSIT_MD
  - file_name: trips_pm.omx
    tables:
      - name: DRIVEALONE_PM
        data_field: DRIVEALONE_PM
      - name: SHARED2_PM
        data_field: SHARED2_PM
      - name: SHARED3_PM
        data_field: SHARED3_PM
      - name: WALK_PM
        data_field: WALK_PM
      - name: BIKE_PM
        data_field: BIKE_PM
  - file_name: trips_pm_tap.omx
    is_tap: True
    tables:
      - name: WALK_TRANSIT_PM
        data_field: WALK_TRANSIT_PM
  - file_name: trips_ev.omx
    tables:
      - name: DRIVEALONE_EV
        data_field: DRIVEALONE_EV
      - name: SHARED2_EV
        data_field: SHARED2_EV
      - name: SHARED3_EV
        data_field: SHARED3_EV
      - name: WALK_EV
        data_field: WALK_EV
      - name: BIKE_EV
        data_field: BIKE_EV
  - file_name: trips_ev_tap.omx
    is_tap: True
    tables:
      - name: WALK_TRANSIT_EV
        data_field: WALK_TRANSIT_EV

CONSTANTS:
  time_periods:
    EA:
      first_hour: 1
      last_hour: 6
    AM:
      first_hour: 7
      last_hour: 12
    MD:
      first_hour: 13
      last_hour: 25
    PM:
      first_hour: 26
      last_hour: 32
    EV:
      first_hour: 33
      last_hour: 48
  # SHARED2 and SHARED3 Occupancies
  OCC_SHARED2: 2.0
  OCC_SHARED3: 3.33
