# misc settings
distance_param: -0.19
walkSpeed: 3
maz_input_fname: land_use.csv
colonia_input_fname: crossBorder_supercolonia.csv
tour_scheduling_probs_input_fname: crossBorder_tourEntryAndReturn.csv
poe_wait_times_input_fname: crossBorder_pointOfEntryWaitTime.csv
stop_frequency_input_fname: crossBorder_stopFrequency.csv
trip_purpose_probs_input_fname: crossBorder_stopPurpose.csv
trip_scheduling_probs_input_fnames:
  outbound: crossBorder_outboundStopDuration.csv
  inbound: crossBorder_inboundStopDuration.csv
mazs_output_fname: mazs_xborder.csv
households_output_fname: households_xborder.csv
persons_output_fname: persons_xborder.csv
tours_output_fname: tours_xborder.csv
tour_scheduling_probs_output_fname: tour_scheduling_probs.csv
tour_scheduling_alts_output_fname: tour_departure_and_duration_alternatives.csv
stop_frequency_alts_output_fname: stop_frequency_alternatives.csv
stop_frequency_coeffs_output_formattable_fname: stop_frequency_coefficients_{purpose}.csv
stop_frequency_expressions_output_formattable_fname: stop_frequency_{purpose}.csv
trip_purpose_probs_output_fname: trip_purpose_probs.csv
trip_scheduling_probs_output_fname: trip_scheduling_probs.csv
skims:
  maz_to_maz:
    walk:
      input_fname: maz_maz_walk.csv
      output_fname: maz_maz_walk.csv
      rename_columns:
        i: OMAZ
        j: DMAZ

# maz_id below is overriden from constants.yaml
# TODO: currently if this is changed, also update input/ie/resident_ie_size_term.csv
poes:
  0:
    name: San Ysidro
    maz_id: 9279
    ext_taz_id: 1
    veh_lanes: 24
    ped_lanes: 15
    start_year: 0
  1:
    name: Otay Mesa
    maz_id: 9387
    ext_taz_id: 2
    veh_lanes: 13
    ped_lanes: 6
    start_year: 0
  2:
    name: Tecate
    maz_id: 22324
    ext_taz_id: 4
    veh_lanes: 2
    ped_lanes: 2
    start_year: 0
  3:
    name: Otay Mesa East
    maz_id: 9402
    ext_taz_id: 3
    veh_lanes: 7
    ped_lanes: 0
    start_year: 2027
tours:
  pass_shares:
    sentri: 0.219
    ready: 0.322
    no_pass: 0.45899999999999996
  num_tours: 101343
  purpose_ids:
    work: 0
    school: 1
    shop: 2
    visit: 3
    other: 4
  purpose_shares_by_pass_type:
    sentri:
      work: 0.2024791434
      school: 0.028223443
      shop: 0.6685167
      visit: 0.023476697
      other: 0.077304037
    ready:
      work: 0.226316
      school: 0.007794038
      shop: 0.631416
      visit: 0.040267183
      other: 0.094206697
    no_pass:
      work: 0.345501
      school: 0.052974068
      shop: 0.476956
      visit: 0.040553855
      other: 0.084014515
wait_time_updating:
  iters: 3
  coeffs:
    std:
      asc: 24.4819
      om_asc: 38.2236
      tc_asc: -31.6399
      vol: 2.138
      vol_om: -1.329
      vol_tc: -1.672
      ea_constant: -17.017
      ev_constant: -33.0233
      ea_om_constant: -29.1815
      ev_om_constant: -11.0587
      ev_tc_constant: 21.8711
    ready:
      asc: 40.0794
      om_asc: -33.5957
      tc_asc: 0
      vol: 2.12e-12
      vol_om: 1.253
      vol_tc: 0
      ea_constant: -1.211E-11
      ev_constant: 1.584E-12
      ea_om_constant: -7.7458
      ev_om_constant: -25.8116
      ev_tc_constant: 0
    sentri:
      asc: 3.5404
      om_asc: -0.3852
      tc_asc: 0
      vol: 0.217
      vol_om: -0.054
      vol_tc: 0
      ea_constant: 0.1617
      ev_constant: 0.4187
      ea_om_constant: 0
      ev_om_constant: -1.1282
      ev_tc_constant: 0
    ped:
      asc: -3.5615
      om_asc: 3.3397
      tc_asc: -2.0119
      vol: 0.2295
      vol_om: -0.1517
      vol_tc: 0.1184
      ea_constant: 3.4151
      ev_constant: 1.9005
      ea_om_constant: -4.477
      ev_om_constant: -3.8144
      ev_tc_constant: 0
