
SPEC: av_ownership.csv
COEFFICIENTS: av_ownership_coeffs.csv

LOGIT_TYPE: MNL

preprocessor:
  SPEC: av_ownership_preprocessor
  DF: choosers
  TABLES:
    - persons

# iterative what-if analysis example
# omit these settings to not iterate
AV_OWNERSHIP_ITERATIONS: 5
AV_OWNERSHIP_TARGET_PERCENT: 0.1
AV_OWNERSHIP_TARGET_PERCENT_TOLERANCE: 0.01
AV_OWNERSHIP_COEFFICIENT_CONSTANT: coef_av_target_share