# read trips table post preprocessor and run expressions to code
# additional data fields, with one data fields for each matrix specified below

preprocessor:
  SPEC: write_trip_matrices_annotate_trips_preprocessor
  DF: trips
  TABLES:
    - tours
    - households
    - land_use

# divide trip counts by household expansion factor
HH_EXPANSION_WEIGHT_COL: sample_rate  # added when households read in

# save preprocessed trips table to pipeline if desired
SAVE_TRIPS_TABLE: True

MATRICES:
  - file_name: autotrips_EA_low.omx
    tables:
      - name: SOVNOTRPDR_EA
        data_field: DRIVEALONE_NOTR_EA_LOW
      - name: SOVTRPDR_EA
        data_field: DRIVEALONE_TR_EA_LOW
      - name: SR2NOTRPDR_EA
        data_field: SHARED2_NOTR_EA_LOW
      - name: SR2TRPDR_EA
        data_field: SHARED2_TR_EA_LOW
      - name: SR3NOTRPDR_EA
        data_field: SHARED3_NOTR_EA_LOW
      - name: SR3TRPDR_EA
        data_field: SHARED3_TR_EA_LOW
  - file_name: autotrips_EA_med.omx
    tables:
      - name: SOVNOTRPDR_EA
        data_field: DRIVEALONE_NOTR_EA_MED
      - name: SOVTRPDR_EA
        data_field: DRIVEALONE_TR_EA_MED
      - name: SR2NOTRPDR_EA
        data_field: SHARED2_NOTR_EA_MED
      - name: SR2TRPDR_EA
        data_field: SHARED2_TR_EA_MED
      - name: SR3NOTRPDR_EA
        data_field: SHARED3_NOTR_EA_MED
      - name: SR3TRPDR_EA
        data_field: SHARED3_TR_EA_MED
  - file_name: autotrips_EA_high.omx
    tables:
      - name: SOVNOTRPDR_EA
        data_field: DRIVEALONE_NOTR_EA_HIGH
      - name: SOVTRPDR_EA
        data_field: DRIVEALONE_TR_EA_HIGH
      - name: SR2NOTRPDR_EA
        data_field: SHARED2_NOTR_EA_HIGH
      - name: SR2TRPDR_EA
        data_field: SHARED2_TR_EA_HIGH
      - name: SR3NOTRPDR_EA
        data_field: SHARED3_NOTR_EA_HIGH
      - name: SR3TRPDR_EA
        data_field: SHARED3_TR_EA_HIGH
  - file_name: autotrips_AM_low.omx
    tables:
      - name: SOVNOTRPDR_AM
        data_field: DRIVEALONE_NOTR_AM_LOW
      - name: SOVTRPDR_AM
        data_field: DRIVEALONE_TR_AM_LOW
      - name: SR2NOTRPDR_AM
        data_field: SHARED2_NOTR_AM_LOW
      - name: SR2TRPDR_AM
        data_field: SHARED2_TR_AM_LOW
      - name: SR3NOTRPDR_AM
        data_field: SHARED3_NOTR_AM_LOW
      - name: SR3TRPDR_AM
        data_field: SHARED3_TR_AM_LOW
  - file_name: autotrips_AM_med.omx
    tables:
      - name: SOVNOTRPDR_AM
        data_field: DRIVEALONE_NOTR_AM_MED
      - name: SOVTRPDR_AM
        data_field: DRIVEALONE_TR_AM_MED
      - name: SR2NOTRPDR_AM
        data_field: SHARED2_NOTR_AM_MED
      - name: SR2TRPDR_AM
        data_field: SHARED2_TR_AM_MED
      - name: SR3NOTRPDR_AM
        data_field: SHARED3_NOTR_AM_MED
      - name: SR3TRPDR_AM
        data_field: SHARED3_TR_AM_MED
  - file_name: autotrips_AM_high.omx
    tables:
      - name: SOVNOTRPDR_AM
        data_field: DRIVEALONE_NOTR_AM_HIGH
      - name: SOVTRPDR_AM
        data_field: DRIVEALONE_TR_AM_HIGH
      - name: SR2NOTRPDR_AM
        data_field: SHARED2_NOTR_AM_HIGH
      - name: SR2TRPDR_AM
        data_field: SHARED2_TR_AM_HIGH
      - name: SR3NOTRPDR_AM
        data_field: SHARED3_NOTR_AM_HIGH
      - name: SR3TRPDR_AM
        data_field: SHARED3_TR_AM_HIGH
  - file_name: autotrips_MD_low.omx
    tables:
      - name: SOVNOTRPDR_MD
        data_field: DRIVEALONE_NOTR_MD_LOW
      - name: SOVTRPDR_MD
        data_field: DRIVEALONE_TR_MD_LOW
      - name: SR2NOTRPDR_MD
        data_field: SHARED2_NOTR_MD_LOW
      - name: SR2TRPDR_MD
        data_field: SHARED2_TR_MD_LOW
      - name: SR3NOTRPDR_MD
        data_field: SHARED3_NOTR_MD_LOW
      - name: SR3TRPDR_MD
        data_field: SHARED3_TR_MD_LOW
  - file_name: autotrips_MD_med.omx
    tables:
      - name: SOVNOTRPDR_MD
        data_field: DRIVEALONE_NOTR_MD_MED
      - name: SOVTRPDR_MD
        data_field: DRIVEALONE_TR_MD_MED
      - name: SR2NOTRPDR_MD
        data_field: SHARED2_NOTR_MD_MED
      - name: SR2TRPDR_MD
        data_field: SHARED2_TR_MD_MED
      - name: SR3NOTRPDR_MD
        data_field: SHARED3_NOTR_MD_MED
      - name: SR3TRPDR_MD
        data_field: SHARED3_TR_MD_MED
  - file_name: autotrips_MD_high.omx
    tables:
      - name: SOVNOTRPDR_MD
        data_field: DRIVEALONE_NOTR_MD_HIGH
      - name: SOVTRPDR_MD
        data_field: DRIVEALONE_TR_MD_HIGH
      - name: SR2NOTRPDR_MD
        data_field: SHARED2_NOTR_MD_HIGH
      - name: SR2TRPDR_MD
        data_field: SHARED2_TR_MD_HIGH
      - name: SR3NOTRPDR_MD
        data_field: SHARED3_NOTR_MD_HIGH
      - name: SR3TRPDR_MD
        data_field: SHARED3_TR_MD_HIGH
  - file_name: autotrips_PM_low.omx
    tables:
      - name: SOVNOTRPDR_PM
        data_field: DRIVEALONE_NOTR_PM_LOW
      - name: SOVTRPDR_PM
        data_field: DRIVEALONE_TR_PM_LOW
      - name: SR2NOTRPDR_PM
        data_field: SHARED2_NOTR_PM_LOW
      - name: SR2TRPDR_PM
        data_field: SHARED2_TR_PM_LOW
      - name: SR3NOTRPDR_PM
        data_field: SHARED3_NOTR_PM_LOW
      - name: SR3TRPDR_PM
        data_field: SHARED3_TR_PM_LOW
  - file_name: autotrips_PM_med.omx
    tables:
      - name: SOVNOTRPDR_PM
        data_field: DRIVEALONE_NOTR_PM_MED
      - name: SOVTRPDR_PM
        data_field: DRIVEALONE_TR_PM_MED
      - name: SR2NOTRPDR_PM
        data_field: SHARED2_NOTR_PM_MED
      - name: SR2TRPDR_PM
        data_field: SHARED2_TR_PM_MED
      - name: SR3NOTRPDR_PM
        data_field: SHARED3_NOTR_PM_MED
      - name: SR3TRPDR_PM
        data_field: SHARED3_TR_PM_MED
  - file_name: autotrips_PM_high.omx
    tables:
      - name: SOVNOTRPDR_PM
        data_field: DRIVEALONE_NOTR_PM_HIGH
      - name: SOVTRPDR_PM
        data_field: DRIVEALONE_TR_PM_HIGH
      - name: SR2NOTRPDR_PM
        data_field: SHARED2_NOTR_PM_HIGH
      - name: SR2TRPDR_PM
        data_field: SHARED2_TR_PM_HIGH
      - name: SR3NOTRPDR_PM
        data_field: SHARED3_NOTR_PM_HIGH
      - name: SR3TRPDR_PM
        data_field: SHARED3_TR_PM_HIGH
  - file_name: autotrips_EV_low.omx
    tables:
      - name: SOVNOTRPDR_EV
        data_field: DRIVEALONE_NOTR_EV_LOW
      - name: SOVTRPDR_EV
        data_field: DRIVEALONE_TR_EV_LOW
      - name: SR2NOTRPDR_EV
        data_field: SHARED2_NOTR_EV_LOW
      - name: SR2TRPDR_EV
        data_field: SHARED2_TR_EV_LOW
      - name: SR3NOTRPDR_EV
        data_field: SHARED3_NOTR_EV_LOW
      - name: SR3TRPDR_EV
        data_field: SHARED3_TR_EV_LOW
  - file_name: autotrips_EV_med.omx
    tables:
      - name: SOVNOTRPDR_EV
        data_field: DRIVEALONE_NOTR_EV_MED
      - name: SOVTRPDR_EV
        data_field: DRIVEALONE_TR_EV_MED
      - name: SR2NOTRPDR_EV
        data_field: SHARED2_NOTR_EV_MED
      - name: SR2TRPDR_EV
        data_field: SHARED2_TR_EV_MED
      - name: SR3NOTRPDR_EV
        data_field: SHARED3_NOTR_EV_MED
      - name: SR3TRPDR_EV
        data_field: SHARED3_TR_EV_MED
  - file_name: autotrips_EV_high.omx
    tables:
      - name: SOVNOTRPDR_EV
        data_field: DRIVEALONE_NOTR_EV_HIGH
      - name: SOVTRPDR_EV
        data_field: DRIVEALONE_TR_EV_HIGH
      - name: SR2NOTRPDR_EV
        data_field: SHARED2_NOTR_EV_HIGH
      - name: SR2TRPDR_EV
        data_field: SHARED2_TR_EV_HIGH
      - name: SR3NOTRPDR_EV
        data_field: SHARED3_NOTR_EV_HIGH
      - name: SR3TRPDR_EV
        data_field: SHARED3_TR_EV_HIGH
  - file_name: trantrips_EA.omx
    tables:
      - name: WALK_SET_set1_EA
        data_field: WALK_LOC_EA
      - name: KNROUT_SET_set1_EA
        data_field: KNR_LOCOUT_EA        
      - name: PNROUT_SET_set1_EA
        data_field: PNR_LOCOUT_EA
      - name: TNCOUT_SET_set1_EA
        data_field: TNC_LOCOUT_EA
      - name: KNRIN_SET_set1_EA
        data_field: KNR_LOCIN_EA        
      - name: PNRIN_SET_set1_EA
        data_field: PNR_LOCIN_EA
      - name: TNCIN_SET_set1_EA
        data_field: TNC_LOCIN_EA        
      - name: WALK_SET_set2_EA
        data_field: WALK_PRM_EA
      - name: KNROUT_SET_set2_EA
        data_field: KNR_PRMOUT_EA        
      - name: PNROUT_SET_set2_EA
        data_field: PNR_PRMOUT_EA
      - name: TNCOUT_SET_set2_EA
        data_field: TNC_PRMOUT_EA
      - name: KNRIN_SET_set2_EA
        data_field: KNR_PRMIN_EA        
      - name: PNRIN_SET_set2_EA
        data_field: PNR_PRMIN_EA
      - name: TNCIN_SET_set2_EA
        data_field: TNC_PRMIN_EA        
      - name: WALK_SET_set3_EA
        data_field: WALK_MIX_EA
      - name: KNROUT_SET_set3_EA
        data_field: KNR_MIXOUT_EA        
      - name: PNROUT_SET_set3_EA
        data_field: PNR_MIXOUT_EA
      - name: TNCOUT_SET_set3_EA
        data_field: TNC_MIXOUT_EA
      - name: KNRIN_SET_set3_EA
        data_field: KNR_MIXIN_EA        
      - name: PNRIN_SET_set3_EA
        data_field: PNR_MIXIN_EA
      - name: TNCIN_SET_set3_EA
        data_field: TNC_MIXIN_EA        
  - file_name: trantrips_AM.omx
    tables:
      - name: WALK_SET_set1_AM
        data_field: WALK_LOC_AM
      - name: KNROUT_SET_set1_AM
        data_field: KNR_LOCOUT_AM        
      - name: PNROUT_SET_set1_AM
        data_field: PNR_LOCOUT_AM
      - name: TNCOUT_SET_set1_AM
        data_field: TNC_LOCOUT_AM
      - name: KNRIN_SET_set1_AM
        data_field: KNR_LOCIN_AM        
      - name: PNRIN_SET_set1_AM
        data_field: PNR_LOCIN_AM
      - name: TNCIN_SET_set1_AM
        data_field: TNC_LOCIN_AM        
      - name: WALK_SET_set2_AM
        data_field: WALK_PRM_AM
      - name: KNROUT_SET_set2_AM
        data_field: KNR_PRMOUT_AM        
      - name: PNROUT_SET_set2_AM
        data_field: PNR_PRMOUT_AM
      - name: TNCOUT_SET_set2_AM
        data_field: TNC_PRMOUT_AM
      - name: KNRIN_SET_set2_AM
        data_field: KNR_PRMIN_AM        
      - name: PNRIN_SET_set2_AM
        data_field: PNR_PRMIN_AM
      - name: TNCIN_SET_set2_AM
        data_field: TNC_PRMIN_AM        
      - name: WALK_SET_set3_AM
        data_field: WALK_MIX_AM
      - name: KNROUT_SET_set3_AM
        data_field: KNR_MIXOUT_AM        
      - name: PNROUT_SET_set3_AM
        data_field: PNR_MIXOUT_AM
      - name: TNCOUT_SET_set3_AM
        data_field: TNC_MIXOUT_AM
      - name: KNRIN_SET_set3_AM
        data_field: KNR_MIXIN_AM        
      - name: PNRIN_SET_set3_AM
        data_field: PNR_MIXIN_AM
      - name: TNCIN_SET_set3_AM
        data_field: TNC_MIXIN_AM        
  - file_name: trantrips_MD.omx
    tables:
      - name: WALK_SET_set1_MD
        data_field: WALK_LOC_MD
      - name: KNROUT_SET_set1_MD
        data_field: KNR_LOCOUT_MD        
      - name: PNROUT_SET_set1_MD
        data_field: PNR_LOCOUT_MD
      - name: TNCOUT_SET_set1_MD
        data_field: TNC_LOCOUT_MD
      - name: KNRIN_SET_set1_MD
        data_field: KNR_LOCIN_MD        
      - name: PNRIN_SET_set1_MD
        data_field: PNR_LOCIN_MD
      - name: TNCIN_SET_set1_MD
        data_field: TNC_LOCIN_MD        
      - name: WALK_SET_set2_MD
        data_field: WALK_PRM_MD
      - name: KNROUT_SET_set2_MD
        data_field: KNR_PRMOUT_MD        
      - name: PNROUT_SET_set2_MD
        data_field: PNR_PRMOUT_MD
      - name: TNCOUT_SET_set2_MD
        data_field: TNC_PRMOUT_MD
      - name: KNRIN_SET_set2_MD
        data_field: KNR_PRMIN_MD        
      - name: PNRIN_SET_set2_MD
        data_field: PNR_PRMIN_MD
      - name: TNCIN_SET_set2_MD
        data_field: TNC_PRMIN_MD        
      - name: WALK_SET_set3_MD
        data_field: WALK_MIX_MD
      - name: KNROUT_SET_set3_MD
        data_field: KNR_MIXOUT_MD        
      - name: PNROUT_SET_set3_MD
        data_field: PNR_MIXOUT_MD
      - name: TNCOUT_SET_set3_MD
        data_field: TNC_MIXOUT_MD
      - name: KNRIN_SET_set3_MD
        data_field: KNR_MIXIN_MD        
      - name: PNRIN_SET_set3_MD
        data_field: PNR_MIXIN_MD
      - name: TNCIN_SET_set3_MD
        data_field: TNC_MIXIN_MD        
  - file_name: trantrips_PM.omx
    tables:
      - name: WALK_SET_set1_PM
        data_field: WALK_LOC_PM
      - name: KNROUT_SET_set1_PM
        data_field: KNR_LOCOUT_PM        
      - name: PNROUT_SET_set1_PM
        data_field: PNR_LOCOUT_PM
      - name: TNCOUT_SET_set1_PM
        data_field: TNC_LOCOUT_PM
      - name: KNRIN_SET_set1_PM
        data_field: KNR_LOCIN_PM        
      - name: PNRIN_SET_set1_PM
        data_field: PNR_LOCIN_PM
      - name: TNCIN_SET_set1_PM
        data_field: TNC_LOCIN_PM        
      - name: WALK_SET_set2_PM
        data_field: WALK_PRM_PM
      - name: KNROUT_SET_set2_PM
        data_field: KNR_PRMOUT_PM        
      - name: PNROUT_SET_set2_PM
        data_field: PNR_PRMOUT_PM
      - name: TNCOUT_SET_set2_PM
        data_field: TNC_PRMOUT_PM
      - name: KNRIN_SET_set2_PM
        data_field: KNR_PRMIN_PM        
      - name: PNRIN_SET_set2_PM
        data_field: PNR_PRMIN_PM
      - name: TNCIN_SET_set2_PM
        data_field: TNC_PRMIN_PM        
      - name: WALK_SET_set3_PM
        data_field: WALK_MIX_PM
      - name: KNROUT_SET_set3_PM
        data_field: KNR_MIXOUT_PM        
      - name: PNROUT_SET_set3_PM
        data_field: PNR_MIXOUT_PM
      - name: TNCOUT_SET_set3_PM
        data_field: TNC_MIXOUT_PM
      - name: KNRIN_SET_set3_PM
        data_field: KNR_MIXIN_PM        
      - name: PNRIN_SET_set3_PM
        data_field: PNR_MIXIN_PM
      - name: TNCIN_SET_set3_PM
        data_field: TNC_MIXIN_PM        
  - file_name: trantrips_EV.omx
    tables:
      - name: WALK_SET_set1_EV
        data_field: WALK_LOC_EV
      - name: KNROUT_SET_set1_EV
        data_field: KNR_LOCOUT_EV        
      - name: PNROUT_SET_set1_EV
        data_field: PNR_LOCOUT_EV
      - name: TNCOUT_SET_set1_EV
        data_field: TNC_LOCOUT_EV
      - name: KNRIN_SET_set1_EV
        data_field: KNR_LOCIN_EV        
      - name: PNRIN_SET_set1_EV
        data_field: PNR_LOCIN_EV
      - name: TNCIN_SET_set1_EV
        data_field: TNC_LOCIN_EV        
      - name: WALK_SET_set2_EV
        data_field: WALK_PRM_EV
      - name: KNROUT_SET_set2_EV
        data_field: KNR_PRMOUT_EV        
      - name: PNROUT_SET_set2_EV
        data_field: PNR_PRMOUT_EV
      - name: TNCOUT_SET_set2_EV
        data_field: TNC_PRMOUT_EV
      - name: KNRIN_SET_set2_EV
        data_field: KNR_PRMIN_EV        
      - name: PNRIN_SET_set2_EV
        data_field: PNR_PRMIN_EV
      - name: TNCIN_SET_set2_EV
        data_field: TNC_PRMIN_EV        
      - name: WALK_SET_set3_EV
        data_field: WALK_MIX_EV
      - name: KNROUT_SET_set3_EV
        data_field: KNR_MIXOUT_EV        
      - name: PNROUT_SET_set3_EV
        data_field: PNR_MIXOUT_EV
      - name: TNCOUT_SET_set3_EV
        data_field: TNC_MIXOUT_EV
      - name: KNRIN_SET_set3_EV
        data_field: KNR_MIXIN_EV        
      - name: PNRIN_SET_set3_EV
        data_field: PNR_MIXIN_EV
      - name: TNCIN_SET_set3_EV
        data_field: TNC_MIXIN_EV        
  - file_name: nmottrips_EA.omx
    tables:
      - name: WALK_EA
        data_field: WALK_EA
      - name: BIKE_EA
        data_field: BIKE_EA
  - file_name: nmottrips_AM.omx
    tables:
      - name: WALK_AM
        data_field: WALK_AM
      - name: BIKE_AM
        data_field: BIKE_AM
  - file_name: nmottrips_MD.omx
    tables:
      - name: WALK_MD
        data_field: WALK_MD
      - name: BIKE_MD
        data_field: BIKE_MD
  - file_name: nmottrips_PM.omx
    tables:
      - name: WALK_PM
        data_field: WALK_PM
      - name: BIKE_PM
        data_field: BIKE_PM
  - file_name: nmottrips_EV.omx
    tables:
      - name: WALK_EV
        data_field: WALK_EV
      - name: BIKE_EV
        data_field: BIKE_EV

CONSTANTS:
  time_periods:
    EA:
      first_hour: 1
      last_hour: 6
    AM:
      first_hour: 7
      last_hour: 12
    MD:
      first_hour: 13
      last_hour: 25
    PM:
      first_hour: 26
      last_hour: 32
    EV:
      first_hour: 33
      last_hour: 48
  vot_threshold_low: 8.81
  vot_threshold_med: 18.00