name: asim_132
channels:
  - conda-forge
  - defaults
dependencies:
  - addict=2.4.0=pyhd8ed1ab_2
  - addicty=2022.2.1=pyhd8ed1ab_0
  - alabaster=0.7.13=pyhd8ed1ab_0
  - altair=4.2.0=pyhd8ed1ab_1
  - anyio=3.6.2=pyhd8ed1ab_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py39ha55989b_3
  - arrow-cpp=10.0.1=h9c18f36_4_cpu
  - asciitree=0.3.3=py_2
  - asttokens=2.2.1=pyhd8ed1ab_0
  - asv=0.5.1=py39h99910a6_2
  - attrs=22.2.0=pyh71513ae_0
  - aws-c-auth=0.6.21=h0fd8c68_3
  - aws-c-cal=0.5.20=h4b5e85a_3
  - aws-c-common=0.8.5=hcfcfb64_0
  - aws-c-compression=0.2.16=h3dc32ea_0
  - aws-c-event-stream=0.2.17=h4de63fd_1
  - aws-c-http=0.7.0=h28290ff_0
  - aws-c-io=0.13.12=hea55e33_1
  - aws-c-mqtt=0.7.13=h0d1d87f_12
  - aws-c-s3=0.2.1=h898862f_4
  - aws-c-sdkutils=0.1.7=h3dc32ea_0
  - aws-checksums=0.1.14=h3dc32ea_0
  - aws-crt-cpp=0.18.16=h977b11b_8
  - aws-sdk-cpp=1.9.379=haf3c795_7
  - babel=2.11.0=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - beautifulsoup4=4.11.1=pyha770c72_0
  - black >= 22.0,<23
  - bleach=5.0.1=pyhd8ed1ab_0
  - blosc=1.21.3=hdccc3a2_0
  - bokeh=2.4.3=pyhd8ed1ab_3
  - boost-cpp=1.78.0=h9f4b32c_1
  - branca=0.6.0=pyhd8ed1ab_0
  - brotli=1.0.9=hcfcfb64_8
  - brotli-bin=1.0.9=hcfcfb64_8
  - brotlipy=0.7.0=py39ha55989b_1005
  - bump2version=1.0.1=pyh9f0ad1d_0
  - bzip2=1.0.8=h8ffe710_4
  - c-ares=1.18.1=h8ffe710_0
  - ca-certificates=2023.05.30=haa95532_0
  - cairo=1.16.0=hd694305_1014
  - cffi=1.15.1=py39h68f70e3_3
  - cfgv=3.3.1=pyhd8ed1ab_0
  - cfitsio=4.1.0=h5a969a9_0
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - click=8.1.3=py39hcbf5309_1
  - click-plugins=1.1.1=py_0
  - cligj=0.7.2=pyhd8ed1ab_1
  - cloudpickle=2.2.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - commonmark=0.9.1=py_0
  - contourpy=1.0.7=py39h1f6ef14_0
  - coverage=6.5.0=py39ha55989b_1
  - coveralls=3.3.1=pyhd8ed1ab_0
  - cryptography=39.0.0=py39hb6bd5e6_0
  - curl=7.87.0=h68f0423_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - cytoolz=0.12.0=py39ha55989b_1
  - dask=2023.3.*
  - dask-core=2023.1.0=pyhd8ed1ab_0
  - dataclasses=0.8=pyhc8e2a94_3
  - debugpy=1.6.5=py39h99910a6_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - descartes=1.1.0=py_4
  - distlib=0.3.6=pyhd8ed1ab_0
  - distributed=2023.1.0=pyhd8ed1ab_0
  - docopt=0.6.2=py_1
  - docutils=0.17.1=py39hcbf5309_3
  - entrypoints=0.4=pyhd8ed1ab_0
  - et_xmlfile=1.0.1=py_1001
  - exceptiongroup=1.1.0=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - expat=2.5.0=h1537add_0
  - fasteners=0.17.3=pyhd8ed1ab_0
  - filelock=3.9.0=pyhd8ed1ab_0
  - fiona=1.8.21=py39h0a5cb73_2
  - flit-core=3.8.0=pyhd8ed1ab_0
  - folium=0.14.0=py39haa95532_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.1=hbde0cde_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.38.0=py39ha55989b_1
  - freetype=2.12.1=h546665d_1
  - freexl=1.0.6=h67ca5e6_1
  - fribidi=1.0.10=h8d14728_0
  - fsspec=2023.1.0=pyhd8ed1ab_0
  - future=0.18.3=pyhd8ed1ab_0
  - gdal=3.5.1=py39hd395a97_1
  - geopandas=0.12.2=pyhd8ed1ab_0
  - geopandas-base=0.12.2=pyha770c72_0
  - geos=3.11.0=h39d44d4_0
  - geotiff=1.7.1=h714bc5f_3
  - getopt-win32=0.1=h8ffe710_0
  - gettext=0.21.1=h5728263_0
  - gflags=2.2.2=ha925a31_1004
  - gh=2.21.2=hd02998f_0
  - git=2.40.1=haa95532_1
  - gitdb=4.0.7=pyhd3eb1b0_0
  - gitpython=3.1.30=py39haa95532_0
  - glib=2.74.1=h12be248_1
  - glib-tools=2.74.1=h12be248_1
  - glog=0.6.0=h4797de2_0
  - graphite2=1.3.13=1000
  - graphviz=7.0.6=h51cb2cd_0
  - gst-plugins-base=1.21.3=h001b923_1
  - gstreamer=1.21.3=h6b5321d_1
  - gts=0.7.6=h7c369d9_2
  - harfbuzz=6.0.0=he256f1b_0
  - hdf4=4.2.15=h1b1b6ef_5
  - hdf5=1.12.1=nompi_h57737ce_104
  - heapdict=1.0.1=py_0
  - icu=70.1=h0e60522_0
  - identify=2.5.13=pyhd8ed1ab_0
  - idna=3.4=pyhd8ed1ab_0
  - imagesize=1.4.1=pyhd8ed1ab_0
  - importlib-metadata=6.0.0=pyha770c72_0
  - importlib_resources=5.10.2=pyhd8ed1ab_0
  - iniconfig=2.0.0=pyhd8ed1ab_0
  - ipykernel=6.14.0=py39h832f523_0
  - ipython=8.4.0=py39hcbf5309_0
  - ipython_genutils=0.2.0=py_1
  - isort
  - jedi=0.18.2=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - joblib=1.2.0=pyhd8ed1ab_0
  - jpeg=9e=h8ffe710_2
  - json5=0.9.5=pyh9f0ad1d_0
  - jsonschema=4.16.0=pyhd8ed1ab_0
  - jupyter_client=7.4.9=pyhd8ed1ab_0
  - jupyter_core=5.1.3=py39hcbf5309_0
  - jupyter_events=0.6.3=pyhd8ed1ab_0
  - jupyter_server=2.1.0=pyhd8ed1ab_0
  - jupyter_server_terminals=0.4.4=pyhd8ed1ab_1
  - jupyterlab=3.5.2=pyhd8ed1ab_0
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - jupyterlab_server=2.16.6=pyhd8ed1ab_0
  - kealib=1.4.15=h8995ca9_0
  - kiwisolver=1.4.4=py39h1f6ef14_1
  - krb5=1.20.1=heb0366b_0
  - larch=5.7.0=py39h5d4886f_0
  - lcms2=2.14=h90d422f_0
  - lerc=4.0.0=h63175ca_0
  - libabseil=20220623.0=cxx17_h1a56200_6
  - libarrow=10.0.1=h226723c_4_cpu
  - libblas=3.9.0=5_hd5c7e75_netlib
  - libbrotlicommon=1.0.9=hcfcfb64_8
  - libbrotlidec=1.0.9=hcfcfb64_8
  - libbrotlienc=1.0.9=hcfcfb64_8
  - libcblas=3.9.0=5_hd5c7e75_netlib
  - libclang=15.0.7=default_h77d9078_0
  - libclang13=15.0.7=default_h77d9078_0
  - libcrc32c=1.1.2=h0e60522_0
  - libcurl=7.87.0=h68f0423_0
  - libdeflate=1.14=hcfcfb64_0
  - libffi=3.4.2=h8ffe710_5
  - libgd=2.3.3=h891f43f_3
  - libgdal=3.5.1=h9e25771_1
  - libglib=2.74.1=he8f3873_1
  - libgoogle-cloud=2.5.0=h5fc25aa_1
  - libgrpc=1.51.1=h6a6baca_0
  - libiconv=1.17=h8ffe710_0
  - libkml=1.3.0=hf2ab4e4_1015
  - liblapack=3.9.0=5_hd5c7e75_netlib
  - libnetcdf=4.8.1=nompi_h1cc8e9d_102
  - libogg=1.3.4=h8ffe710_1
  - libpng=1.6.39=h19919ed_0
  - libpq=14.5=ha9684e8_5
  - libprotobuf=3.21.12=h12be248_0
  - librttopo=1.1.0=h2842628_11
  - libsodium=1.0.18=h8d14728_1
  - libspatialindex=1.9.3=h39d44d4_4
  - libspatialite=5.0.1=hd9530bf_19
  - libsqlite=3.40.0=hcfcfb64_0
  - libssh2=1.10.0=h9a1e1f7_3
  - libthrift=0.16.0=h9ce19ad_2
  - libtiff=4.4.0=hc4f729c_5
  - libutf8proc=2.8.0=h82a8f57_0
  - libvorbis=1.3.7=h0e60522_0
  - libwebp=1.2.4=hcfcfb64_1
  - libwebp-base=1.2.4=h8ffe710_0
  - libxcb=1.13=hcd874cb_1004
  - libxml2=2.10.3=hc3477c8_0
  - libxslt=1.1.37=h0192164_0
  - libzip=1.9.2=h519de47_1
  - libzlib=1.2.13=hcfcfb64_4
  - llvmlite=0.39.1=py39hd28a505_1
  - locket=1.0.0=pyhd8ed1ab_0
  - lxml=4.9.2=py39h0942119_0
  - lz4=4.2.0=py39hf617134_0
  - lz4-c=1.9.3=h8ffe710_1
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - mapclassify=2.5.0=pyhd8ed1ab_1
  - markdown-it-py=2.1.0=pyhd8ed1ab_0
  - markupsafe=2.1.2=py39ha55989b_0
  - matplotlib=3.6.3=py39hcbf5309_0
  - matplotlib-base=3.6.3=py39haf65ace_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mdit-py-plugins=0.3.3=pyhd8ed1ab_0
  - mdurl=0.1.0=pyhd8ed1ab_0
  - mistune=2.0.4=pyhd8ed1ab_0
  - mock=5.0.1=pyhd8ed1ab_0
  - msgpack-python=1.0.4=py39h1f6ef14_1
  - msys2-conda-epoch=20160418=1
  - munch=2.5.0=py_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - myst-parser=0.18.1=pyhd8ed1ab_0
  - nbclassic=0.4.8=pyhd8ed1ab_0
  - nbclient=0.7.2=pyhd8ed1ab_0
  - nbconvert=7.2.8=pyhd8ed1ab_0
  - nbconvert-core=7.2.8=pyhd8ed1ab_0
  - nbconvert-pandoc=7.2.8=pyhd8ed1ab_0
  - nbformat=5.7.3=pyhd8ed1ab_0
  - nbmake
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - networkx=3.0=pyhd8ed1ab_0
  - nodeenv=1.7.0=pyhd8ed1ab_0
  - nomkl=1.0=h5ca1d4c_0
  - notebook=6.5.2=pyha770c72_1
  - notebook-shim=0.2.2=pyhd8ed1ab_0
  - numba = 0.57.*
  - numcodecs=0.11.0=py39h99910a6_1
  - numexpr=2.8.3=py39hdba7acd_101
  - numpy = 1.23.*
  - numpydoc=1.5.0=pyhd8ed1ab_0
  - openjpeg=2.5.0=hc9384bd_1
  - openmatrix=0.3.5.0=pyhd8ed1ab_0
  - openpyxl=3.0.10=py39ha55989b_2
  - openssl=3.0.10=h2bbff1b_0
  - orca=1.8=pyhd8ed1ab_0
  - packaging=23.0=pyhd8ed1ab_0
  - pandas=1.5.3=py39h2ba5b7c_0
  - pandera >= 0.15, <0.18.1
  - pandoc=2.19.2=h57928b3_1
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - pango=1.50.12=hdffb7b3_1
  - parquet-cpp=1.5.1=2
  - parso=0.8.3=pyhd8ed1ab_0
  - partd=1.3.0=pyhd8ed1ab_0
  - pathspec=0.10.3=pyhd8ed1ab_0
  - patsy=0.5.3=pyhd8ed1ab_0
  - pcre=8.45=h0e60522_0
  - pcre2=10.40=h17e33f8_0
  - pickleshare=0.7.5=py_1003
  - pillow=9.2.0=py39h595c93f_3
  - pip=22.3.1=pyhd8ed1ab_0
  - pixman=0.40.0=h8ffe710_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - platformdirs = 3.2.*
  - pluggy=1.0.0=pyhd8ed1ab_5
  - ply=3.11=py_1
  - pooch=1.6.0=pyhd8ed1ab_0
  - poppler=22.04.0=hb57f792_3
  - poppler-data=0.4.11=hd8ed1ab_0
  - postgresql=14.5=hd87cd2b_5
  - pre-commit=2.21.0=py39hcbf5309_0
  - proj=9.0.1=h1cfcee9_1
  - prometheus_client=0.15.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.36=pyha770c72_0
  - psutil=5.9.4=py39ha55989b_0
  - pthread-stubs=0.4=hcd874cb_1001
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pyarrow = 11.*
  - pycodestyle=2.10.0=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pydata-sphinx-theme=0.12.0=pyhd8ed1ab_0
  - pydantic = 2.6.*
  - pydot=1.4.2=py39hcbf5309_3
  - pygments=2.14.0=pyhd8ed1ab_0
  - pyinstrument=4.4.0=py39ha55989b_0
  - pyopenssl=23.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyproj=3.4.0=py39h2de216b_0
  - pypyr = 5.8.*
  - pyqt=5.15.7=py39hb77abff_2
  - pyqt5-sip=12.11.0=py39h99910a6_2
  - pyrsistent=0.19.3=py39ha55989b_0
  - pysocks=1.7.1=py39hcbf5309_5
  - pytables >=3.7
  - pytest=7.2.1=pyhd8ed1ab_0
  - pytest-cov=4.0.0=pyhd8ed1ab_0
  - pytest-datadir=1.4.1=pyhd8ed1ab_0
  - pytest-regressions=2.4.2=pyhd8ed1ab_0
  - python=3.10
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.16.2=pyhd8ed1ab_0
  - python-json-logger=2.0.4=pyhd8ed1ab_0
  - python_abi=3.9=3_cp39
  - pytz=2022.7.1=pyhd8ed1ab_0
  - pywin32=304=py39h99910a6_2
  - pywinpty=2.0.10=py39h99910a6_0
  - pyyaml=6.0=py39ha55989b_5
  - pyzmq=25.0.0=py39hea35a22_0
  - qt-main=5.15.6=h9580fe5_5
  - re2=2022.06.01=h0e60522_1
  - requests=2.28.2=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_0
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rich = 13.3.*
  - rtree=1.0.1=py39h09fdee3_1
  - ruamel.yaml=0.17.21=py39ha55989b_2
  - ruamel.yaml.clib=0.2.7=py39ha55989b_1
  - ruby=3.1.2=h8ed59c0_0
  - ruff
  - scikit-learn=1.2.0=py39h6fe01c0_0
  - scipy=1.10.0=py39hfbf2dce_0
  - seaborn=0.12.2=hd8ed1ab_0
  - seaborn-base=0.12.2=pyhd8ed1ab_0
  - setuptools_scm
  - send2trash=1.8.0=pyhd8ed1ab_0
  - sharrow >= 2.9.1
  - simwrapper=1.8.5=pyhd8ed1ab_0
  - sip=6.7.5=py39h99910a6_0
  - six=1.16.0=pyh6c4a22f_0
  - smmap=4.0.0=pyhd3eb1b0_0
  - snakeviz=2.1.1=pyhd8ed1ab_0
  - snappy=1.1.9=hfb803bf_2
  - sniffio=1.3.0=pyhd8ed1ab_0
  - snowballstemmer=2.2.0=pyhd8ed1ab_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_0
  - soupsieve=2.3.2.post1=pyhd8ed1ab_0
  - sparse=0.13.0=pyhd8ed1ab_0
  - sphinx = 6.1.*
  - sphinx-argparse = 0.4.*
  - sphinx_rtd_theme = 1.2.*
  - sphinxcontrib-applehelp=1.0.2=py_0
  - sphinxcontrib-devhelp=1.0.2=py_0
  - sphinxcontrib-htmlhelp=2.0.0=pyhd8ed1ab_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.3=py_0
  - sphinxcontrib-serializinghtml=1.1.5=pyhd8ed1ab_2
  - sqlite=3.40.0=hcfcfb64_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - statsmodels=0.13.5=py39hc266a54_2
  - tblib=1.7.0=pyhd8ed1ab_0
  - terminado=0.15.0=py39hcbf5309_0
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - tiledb=2.9.5=h3132609_0
  - tinycss2=1.2.1=pyhd8ed1ab_0
  - tk=8.6.12=h8ffe710_0
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - tomli-w=1.0.0=pyhd8ed1ab_0
  - toolz=0.12.0=pyhd8ed1ab_0
  - tornado=6.2=py39ha55989b_1
  - tqdm=4.64.1=pyhd8ed1ab_0
  - traitlets=5.8.1=pyhd8ed1ab_0
  - typing-extensions=4.4.0=hd8ed1ab_0
  - typing_extensions=4.4.0=pyha770c72_0
  - tzdata=2022g=h191b570_0
  - ucrt=10.0.22621.0=h57928b3_0
  - ukkonen=1.0.1=py39h1f6ef14_3
  - unicodedata2=15.0.0=py39ha55989b_0
  - urllib3=1.26.14=pyhd8ed1ab_0
  - vc=14.3=hb25d44b_17
  - vc14_runtime=14.34.31931=h5081d32_13
  - virtualenv=20.17.1=py39hcbf5309_0
  - vs2015_runtime=14.34.31931=h4c5c07a_10
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - webencodings=0.5.1=py_1
  - websocket-client=1.4.2=pyhd8ed1ab_0
  - wheel=0.38.4=pyhd8ed1ab_0
  - win_inet_pton=1.1.0=py39hcbf5309_5
  - winpty=0.4.3=4
  - xarray = 2023.2.*
  - xerces-c=3.2.4=h63175ca_1
  - xlsxwriter=3.0.7=pyhd8ed1ab_0
  - xmle=0.1.24=pyhd8ed1ab_0
  - xorg-kbproto=1.0.7=hcd874cb_1002
  - xorg-libice=1.0.10=hcd874cb_0
  - xorg-libsm=1.2.3=hcd874cb_1000
  - xorg-libx11=1.7.2=hcd874cb_0
  - xorg-libxau=1.0.9=hcd874cb_0
  - xorg-libxdmcp=1.1.3=hcd874cb_0
  - xorg-libxext=1.3.4=hcd874cb_1
  - xorg-libxpm=3.5.13=hcd874cb_0
  - xorg-libxt=1.2.1=hcd874cb_2
  - xorg-xextproto=7.3.0=hcd874cb_1002
  - xorg-xproto=7.0.31=hcd874cb_1007
  - xyzservices=2022.9.0=pyhd8ed1ab_0
  - xz=5.2.6=h8d14728_0
  - yaml=0.2.5=h8ffe710_2
  - yamllint=1.29.0=pyhd8ed1ab_0
  - zarr = 2.14.*
  - zeromq=4.3.4=h0e60522_1
  - zict=2.2.0=pyhd8ed1ab_0
  - zipp=3.11.0=pyhd8ed1ab_0
  - zlib=1.2.13=hcfcfb64_4
  - zstandard
  - zstd=1.5.2=h12be248_5
  - pip:
    - alphashape==1.3.1
    - autodoc_pydantic
    - azure-core==1.28.0
    - azure-storage-blob==12.17.0
    - certifi==2022.12.7
    - click-log==0.4.0
    - cython==0.29.33
    - geographiclib==2.0
    - geonetworkx==0.5.3
    - geopy==2.3.0
    - isodate==0.6.1
    - nose==1.3.7
    - osmnx==1.3.1.post0
    - pandana==0.6.1
    - pyogrio==0.6.0
    - setuptools==66.1.0
    - shapely==2.0.1
    - trimesh==3.22.0
    - wring

